# Generated by Django 6.0.3 on 2026-03-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatCiudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cat_ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatEstados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cat_estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatEstatusPoliza',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_estatus_poliza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatEstatusSiniestro',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cat_estatus_siniestro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatMarcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cat_marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatMetodosPago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_metodos_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatModelos',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cat_modelos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatMonedas',
            fields=[
                ('id_moneda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_monedas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatPaises',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_iso', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'cat_paises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(max_length=13)),
                ('tipo_documento', models.CharField(max_length=3)),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('profesion_oficio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cobranzas',
            fields=[
                ('id_cobranza', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('referencia', models.CharField(max_length=50)),
                ('banco_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('forma_pago', models.CharField(max_length=13)),
                ('estatus', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'cobranzas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompaniasSeguros',
            fields=[
                ('id_compania', models.AutoField(primary_key=True, serialize=False)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('persona_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companias_seguros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigComisiones',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_acuerdo', models.DateField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'config_comisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'cotizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('suma_asegurada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prima_anual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deducible', models.CharField(blank=True, max_length=100, null=True)),
                ('seleccionada', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_cotizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Financiadoras',
            fields=[
                ('id_financiadora', models.AutoField(primary_key=True, serialize=False)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tasa_interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financiadoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngresosComisiones',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('monto_comision_recibida', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_cobro_comision', models.DateTimeField(blank=True, null=True)),
                ('numero_referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus_conciliacion', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ingresos_comisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intermediarios',
            fields=[
                ('id_intermediario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('codigo_sudeaseg', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intermediarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Polizas',
            fields=[
                ('id_poliza', models.AutoField(primary_key=True, serialize=False)),
                ('numero_poliza', models.CharField(max_length=50)),
                ('id_ramo', models.IntegerField()),
                ('id_intermediario', models.IntegerField(blank=True, null=True)),
                ('suma_asegurada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prima_neta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_emision', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polizas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramos',
            fields=[
                ('id_ramo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ramo', models.CharField(max_length=100)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ramos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecibosPrimas',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_vencimiento', models.DateField()),
                ('estatus_cobro', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'recibos_primas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Siniestros',
            fields=[
                ('id_siniestro', models.AutoField(primary_key=True, serialize=False)),
                ('numero_siniestro', models.CharField(max_length=50)),
                ('fecha_ocurrencia', models.DateTimeField()),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('descripcion_evento', models.TextField()),
                ('lugar_evento', models.CharField(blank=True, max_length=200, null=True)),
                ('monto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('nombre_contacto_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'siniestros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('id_vehiculo', models.IntegerField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('estatus_suscripcion', models.CharField(blank=True, max_length=19, null=True)),
                ('observaciones_tecnicas', models.TextField(blank=True, null=True)),
                ('monto_inspeccion', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'suscripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.IntegerField(blank=True, null=True)),
                ('bloqueado', models.IntegerField(blank=True, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('serial_motor', models.CharField(max_length=50)),
                ('serial_carroceria', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(help_text='Ej: Administrador, Corredor, Analista', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.BooleanField(default=True, help_text='True = Activo, False = Inactivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'perfiles_usuario',
            },
        ),
    ]
