# Generated by Django 6.0.3 on 2026-03-08 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatEstados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cat_estados',
            },
        ),
        migrations.CreateModel(
            name='CatEstatusPoliza',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cat_estatus_poliza',
            },
        ),
        migrations.CreateModel(
            name='CatEstatusSiniestro',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cat_estatus_siniestro',
            },
        ),
        migrations.CreateModel(
            name='CatMarcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cat_marcas',
            },
        ),
        migrations.CreateModel(
            name='CatMetodosPago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cat_metodos_pago',
            },
        ),
        migrations.CreateModel(
            name='CatMonedas',
            fields=[
                ('id_moneda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cat_monedas',
            },
        ),
        migrations.CreateModel(
            name='CatPaises',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_iso', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'cat_paises',
            },
        ),
        migrations.CreateModel(
            name='CompaniasSeguros',
            fields=[
                ('id_compania', models.AutoField(primary_key=True, serialize=False)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('persona_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'companias_seguros',
            },
        ),
        migrations.CreateModel(
            name='Financiadoras',
            fields=[
                ('id_financiadora', models.AutoField(primary_key=True, serialize=False)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tasa_interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'financiadoras',
            },
        ),
        migrations.CreateModel(
            name='Intermediarios',
            fields=[
                ('id_intermediario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('codigo_sudeaseg', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'intermediarios',
            },
        ),
        migrations.CreateModel(
            name='Ramos',
            fields=[
                ('id_ramo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ramo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ramos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='CatCiudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='core.catestados')),
            ],
            options={
                'db_table': 'cat_ciudades',
            },
        ),
        migrations.CreateModel(
            name='CatModelos',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_marca', models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.CASCADE, to='core.catmarcas')),
            ],
            options={
                'db_table': 'cat_modelos',
            },
        ),
        migrations.AddField(
            model_name='catestados',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='core.catpaises'),
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICA', 'Jurídica'), ('GUBERNAMENTAL', 'Gubernamental')], max_length=20)),
                ('tipo_documento', models.CharField(max_length=3)),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('profesion_oficio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_ciudad', models.ForeignKey(blank=True, db_column='id_ciudad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catciudades')),
            ],
            options={
                'db_table': 'clientes',
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('id_ramo', models.ForeignKey(db_column='id_ramo', on_delete=django.db.models.deletion.CASCADE, to='core.ramos')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Polizas',
            fields=[
                ('id_poliza', models.AutoField(primary_key=True, serialize=False)),
                ('numero_poliza', models.CharField(max_length=50)),
                ('suma_asegurada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prima_neta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_emision', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='core.clientes')),
                ('id_compania', models.ForeignKey(db_column='id_compania', on_delete=django.db.models.deletion.CASCADE, to='core.companiasseguros')),
                ('id_estatus', models.ForeignKey(db_column='id_estatus', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.catestatuspoliza')),
                ('id_moneda', models.ForeignKey(db_column='id_moneda', on_delete=django.db.models.deletion.CASCADE, to='core.catmonedas')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
                ('id_ramo', models.ForeignKey(db_column='id_ramo', on_delete=django.db.models.deletion.CASCADE, to='core.ramos')),
            ],
            options={
                'db_table': 'polizas',
            },
        ),
        migrations.CreateModel(
            name='RecibosPrimas',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_vencimiento', models.DateField()),
                ('estatus_cobro', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20)),
                ('id_poliza', models.ForeignKey(db_column='id_poliza', on_delete=django.db.models.deletion.CASCADE, to='core.polizas')),
            ],
            options={
                'db_table': 'recibos_primas',
            },
        ),
        migrations.CreateModel(
            name='Siniestros',
            fields=[
                ('id_siniestro', models.AutoField(primary_key=True, serialize=False)),
                ('numero_siniestro', models.CharField(max_length=50)),
                ('fecha_ocurrencia', models.DateTimeField()),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_evento', models.TextField()),
                ('lugar_evento', models.CharField(blank=True, max_length=200, null=True)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monto_aprobado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nombre_contacto_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_estatus', models.ForeignKey(db_column='id_estatus', on_delete=django.db.models.deletion.CASCADE, to='core.catestatussiniestro')),
                ('id_poliza', models.ForeignKey(db_column='id_poliza', on_delete=django.db.models.deletion.CASCADE, to='core.polizas')),
            ],
            options={
                'db_table': 'siniestros',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='core.roles')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('serial_motor', models.CharField(max_length=50)),
                ('serial_carroceria', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='core.clientes')),
                ('id_modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.CASCADE, to='core.catmodelos')),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.AddField(
            model_name='polizas',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehiculos'),
        ),
    ]
