# Generated by Django 6.0.3 on 2026-03-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranzas',
            fields=[
                ('id_cobranza', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('referencia', models.CharField(max_length=50)),
                ('banco_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('forma_pago', models.CharField(max_length=13)),
                ('estatus', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'cobranzas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigComisiones',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_acuerdo', models.DateField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'config_comisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'cotizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('suma_asegurada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prima_anual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deducible', models.CharField(blank=True, max_length=100, null=True)),
                ('seleccionada', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_cotizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngresosComisiones',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('monto_comision_recibida', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_cobro_comision', models.DateTimeField(blank=True, null=True)),
                ('numero_referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus_conciliacion', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ingresos_comisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('id_vehiculo', models.IntegerField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('estatus_suscripcion', models.CharField(blank=True, max_length=19, null=True)),
                ('observaciones_tecnicas', models.TextField(blank=True, null=True)),
                ('monto_inspeccion', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'suscripciones',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='catciudades',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catestados',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catestatuspoliza',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catestatussiniestro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catmarcas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catmetodospago',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catmodelos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catmonedas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catpaises',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='companiasseguros',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='financiadoras',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='intermediarios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='polizas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ramos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recibosprimas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='siniestros',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vehiculos',
            options={'managed': False},
        ),
    ]
