# Generated by Django 6.0.3 on 2026-03-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={},
        ),
    ]
