# Generated by Django 6.0.3 on 2026-03-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cobranzas_configcomisiones_cotizaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(help_text='Ej: Administrador, Corredor, Analista', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.BooleanField(default=True, help_text='True = Activo, False = Inactivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'perfiles_usuario',
                'managed': False,
            },
        ),
    ]
