# Generated by Django 6.0.3 on 2026-03-21 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfilusuario_options_alter_roles_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='activo',
        ),
        migrations.AddField(
            model_name='roles',
            name='estatus',
            field=models.CharField(default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='roles',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roles',
            name='nombre_rol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
